disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - colon
  - function_parameter_count
  
opt_in_rules:
  - empty_count
  - missing_docs
  
excluded:
#  - Carthage
  - Pods
  
included:
  - AppDesigner
  
file_length:
  warning: 500
  error: 600
